algoritmo "PASSO 03 - 26 - CONDIÇÕES COMPOSTAS"
var
   v1, v2: inteiro
inicio
   Escreval ("Informe o primeiro valor:")
   Leia (v1)
   Escreval ("Informe o segundo valor:")
   Leia (v2)
   se v1 > v2 então
      escreva ("O primeiro valor é maior!")
   fimse
   se v1 < v2 então
      escreva ("O segundo valor é maior!")
   fimse
   se v1 = v2 então
      escreva ("Não existe valor maior, os dois são iguais!")
   fimse
fimalgoritmo